apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s:drycc-resources" .Release.Namespace | quote }}
  labels:
    app: drycc-resources
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s:drycc-resources" .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: drycc-resources
    namespace: {{ .Release.Namespace }}
