apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-resources
  labels:
    app: drycc-resources
    heritage: drycc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: drycc-resources
  template:
    metadata:
      labels:
        app: drycc-resources
    spec:
      serviceAccountName: drycc-resources
      initContainers:
        - name: drycc-resources-init
          image: registry.drycc.cc/drycc/python-dev:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - netcat
            - -v
            - -u
            - $(DRYCC_DATABASE_URL),$(DRYCC_VALKEY_URL)
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: password
            - name: DRYCC_DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@drycc-database.{{ .Release.Namespace }}.svc:5432/resources"
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-creds
                  key: password
            - name: DRYCC_VALKEY_URL
              value: "redis://:$(VALKEY_PASSWORD)@drycc-valkey.{{ .Release.Namespace }}.svc:16379/9"
      containers:
        - name: drycc-resources
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: DRYCC_CONTROLLER_URL
              value: {{ .Values.controller.url | quote }}
            - name: DRYCC_CONTROLLER_VERIFY_TLS
              value: {{ .Values.controller.verifyTLS | quote }}
            - name: DRYCC_CONTROLLER_AUTH_CACHE_TTL
              value: {{ .Values.controller.authCacheTTL | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: password
            - name: DRYCC_DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@drycc-database.{{ .Release.Namespace }}.svc:5432/resources"
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-creds
                  key: password
            - name: DRYCC_VALKEY_URL
              value: "redis://:$(VALKEY_PASSWORD)@drycc-valkey.{{ .Release.Namespace }}.svc:16379/9"
            - name: K8S_API_VERIFY_TLS
              value: {{ .Values.kubernetes.apiVerifyTLS | quote }}
            {{- with .Values.workflowManager.url }}
            - name: WORKFLOW_MANAGER_URL
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.workflowManager.accessKey }}
            - name: WORKFLOW_MANAGER_ACCESS_KEY
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.quickwit.indexerUrl }}
            - name: QUICKWIT_INDEXER_URL
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.quickwit.logIndexPrefix }}
            - name: QUICKWIT_LOG_INDEX_PREFIX
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.secretKey }}
            - name: DRYCC_SECRET_KEY
              value: {{ . | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
