# Generated by Django 5.2.14 on 2026-06-02 08:26

import api.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(db_index=True, max_length=63, validators=[api.utils.validate_label])),
                ('workspace_id', models.CharField(db_index=True, max_length=63)),
                ('name', models.CharField(max_length=63, validators=[api.utils.validate_label])),
                ('plan', models.CharField(max_length=128)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.TextField(blank=True, null=True)),
                ('binding', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'indexes': [models.Index(fields=['app_id', 'workspace_id'], name='api_resourc_app_id_6a3579_idx')],
                'unique_together': {('app_id', 'name')},
            },
        ),
    ]
